version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hotel-booking-sqlserver-prod
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASSWORD:-HotelBooking1234!}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data_prod:/var/opt/mssql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - hotel-booking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SQL_SERVER_PASSWORD:-HotelBooking1234!} -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5

  # API Gateway Service
  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/HotelBooking.ApiGateway/Dockerfile
    container_name: hotel-booking-api-gateway-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HotelBookingSystem;User Id=sa;Password=${SQL_SERVER_PASSWORD:-HotelBooking1234!};TrustServerCertificate=true;
      - ServiceUrls__BookingService=http://booking-service:80
      - ServiceUrls__AnalyticsService=http://analytics-service:80
    ports:
      - "80:80"
    depends_on:
      sqlserver:
        condition: service_healthy
      booking-service:
        condition: service_started
      analytics-service:
        condition: service_started
    networks:
      - hotel-booking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Booking Service
  booking-service:
    build:
      context: .
      dockerfile: src/Services/HotelBooking.BookingService/Dockerfile
    container_name: hotel-booking-booking-service-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HotelBookingSystem;User Id=sa;Password=${SQL_SERVER_PASSWORD:-HotelBooking1234!};TrustServerCertificate=true;
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - hotel-booking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Analytics Service
  analytics-service:
    build:
      context: .
      dockerfile: src/Services/HotelBooking.AnalyticsService/Dockerfile
    container_name: hotel-booking-analytics-service-prod
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=HotelBookingSystem;User Id=sa;Password=${SQL_SERVER_PASSWORD:-HotelBooking1234!};TrustServerCertificate=true;
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - hotel-booking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build:
      context: ./hotel-booking-frontend
      dockerfile: Dockerfile
    container_name: hotel-booking-frontend-prod
    environment:
      - REACT_APP_API_BASE_URL=http://api-gateway
    depends_on:
      - api-gateway
    networks:
      - hotel-booking-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: hotel-booking-nginx-prod
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - api-gateway
    networks:
      - hotel-booking-network
    restart: unless-stopped

volumes:
  sqlserver_data_prod:
    driver: local

networks:
  hotel-booking-network:
    driver: bridge
